import type {
  IncidentReport,
  ScenarioDefinition,
  ScenarioState,
} from "./simulationAdapter";

/**
 * The case, as a document somebody can take away.
 *
 * The Case view already says of its timeline: "Your collected evidence in
 * order. This is the report." It was not one -- there was no way to get it
 * out of the page, which for a product whose whole output is an analyst's
 * write-up is most of the value left on the table. An instructor reviewing a
 * run, or an analyst pasting into a ticket, needs the text.
 *
 * Markdown rather than JSON: the audience is a person, and the destinations
 * are ticketing systems, chat and documents, all of which render it.
 *
 * Everything here is read from state the run already holds. The report
 * asserts nothing the console did not already show, which is the same rule
 * the case itself follows -- nothing is authored twice.
 */

export interface CaseReportInput {
  readonly scenario: ScenarioDefinition;
  readonly state: ScenarioState;
  readonly report: IncidentReport;
  readonly questionAnswers: Readonly<
    Record<string, string>
  >;
  readonly questionScore: {
    readonly earned: number;
    readonly available: number;
  };
  readonly formatTimestamp: (
    timestamp: string | undefined,
  ) => string;
}

function section(
  heading: string,
  body: readonly string[],
): readonly string[] {
  return body.length > 0
    ? [`## ${heading}`, "", ...body, ""]
    : [];
}

export function buildCaseReport(
  input: CaseReportInput,
): string {
  const {
    scenario,
    state,
    report,
    questionAnswers,
    questionScore,
    formatTimestamp,
  } = input;

  const lines: string[] = [
    `# ${scenario.name}`,
    "",
    scenario.description,
    "",
    `- **Status:** ${state.finalized ? state.outcome.status : "in progress"}`,
    `- **Phase:** ${report.phase}`,
    `- **Evidence collected:** ${report.evidenceCount}`,
    `- **Entities in scope:** ${report.entityCount}`,
    "",
  ];

  /*
    Only after finalizing. Before that the score is not settled, and writing
    a number into a document people will paste elsewhere would give it a
    permanence it has not earned.
  */
  if (state.finalized) {
    lines.push(
      `- **Objective score:** ${state.score.percentage}%`,
      `- **Questions:** ${questionScore.earned}/${questionScore.available} points`,
      "",
    );
  }

  lines.push(
    ...section(
      "Response objectives",
      state.outcome.objectives.map(
        (objective) =>
          `- [${objective.met ? "x" : " "}] ${objective.label} — ${objective.description}`,
      ),
    ),
  );

  lines.push(
    ...section(
      "Hypotheses",
      report.supportedHypotheses.map(
        (hypothesis) =>
          `- ${hypothesis.statement}`,
      ),
    ),
  );

  lines.push(
    ...section(
      "External indicators",
      report.externalIndicators.map(
        (indicator) =>
          `- \`${indicator.value}\` (${indicator.kind.replaceAll(
            "_",
            " ",
          )})`,
      ),
    ),
  );

  lines.push(
    ...section(
      "Evidence",
      report.timeline.map(
        (record) =>
          `- **${formatTimestamp(
            record.timestamp,
          )}** — ${record.eventType} — ${record.message}`,
      ),
    ),
  );

  lines.push(
    ...section(
      "Decisions",
      report.decisions.map(
        (decision) =>
          `- **${decision.summary}**${
            decision.rationale
              ? ` — ${decision.rationale}`
              : ""
          }`,
      ),
    ),
  );

  lines.push(
    ...section(
      "Open tasks",
      report.openTasks.map(
        (task) =>
          `- ${task.title} (${task.owner})`,
      ),
    ),
  );

  const answered = (
    scenario.questions ?? []
  )
    .map((question) => ({
      question,
      answer: (
        questionAnswers[question.id] ??
        ""
      ).trim(),
    }))
    .filter(
      (entry) => entry.answer.length > 0,
    );

  lines.push(
    ...section(
      "Investigation answers",
      answered.map(
        (entry) =>
          `- **${entry.question.prompt}**\n  ${entry.answer}`,
      ),
    ),
  );

  // Named so a reader knows the numbers above are reproducible rather than
  // a one-off, which is the whole premise of a seeded generator.
  lines.push(
    "---",
    "",
    `Generated by Endomorph from scenario \`${scenario.id}\`. The same scenario replays identically.`,
    "",
  );

  return lines.join("\n");
}
